import {
  Activity,
  ArrowDownUp,
  Bell,
  BookOpen,
  Brain,
  BrainCircuit,
  CircleCheck,
  Database,
  FileText,
  GitCommit,
  Globe,
  GraduationCap,
  Hand,
  History,
  Keyboard,
  Layers,
  LayoutGrid,
  Lightbulb,
  List,
  MessageCircleQuestion,
  MessageSquareMore,
  Monitor,
  MousePointerClick,
  Move,
  Paperclip,
  Pencil,
  RotateCcw,
  ScanEye,
  Search,
  Sparkles,
  Square,
  Target,
  Trash2,
  Wrench,
} from "lucide-react-native";
import type { LucideIcon } from "lucide-react-native";
import { getToolIconName, type ToolIconName } from "../../../../src/common/constants/toolIcons";
import { colors } from "../theme";

const toolIcons: Record<ToolIconName, LucideIcon> = {
  Activity,
  ArrowDownUp,
  Bell,
  BookOpen,
  Brain,
  BrainCircuit,
  CircleCheck,
  Database,
  FileText,
  GitCommit,
  Globe,
  GraduationCap,
  Hand,
  History,
  Keyboard,
  Layers,
  LayoutGrid,
  Lightbulb,
  List,
  MessageCircleQuestion,
  MessageSquareMore,
  Monitor,
  MousePointerClick,
  Move,
  Paperclip,
  Pencil,
  RotateCcw,
  ScanEye,
  Search,
  Sparkles,
  Square,
  Target,
  Trash2,
  Wrench,
};

export function ToolIcon(props: { toolName: string }) {
  const Icon = toolIcons[getToolIconName(props.toolName)];
  return <Icon size={16} color={colors.muted} aria-hidden />;
}
